
[font]
size = 12

[font.offset]
y = -2

[font.normal]
family = "Cascadia Code"
#family = "freemono"
#family = "DejaVuSansMono"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

